[deploy_config]
salt = "ethers phoenix"
chains = ["zora_sepolia","base_sepolia","Lisk sepolia","mode_sepolia","superseed_sepolia"]

[token]
owner_address = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
name = "TestSuperchainERC20"
symbol = "TSU"
decimals = 18
