[rpc_endpoints]
op_chain_a = "http://127.0.0.1:9545"
op_chain_b = "http://127.0.0.1:9546"
lisk_sepolia = "https://rpc.sepolia-api.lisk.com"

[profile.default]
src = "src"
script = "scripts"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

fs_permissions = [
  { access='read', path='./configs' },
  { access='read', path='./test' },
  { access='write', path='./deployment.json' }
]

remappings = [
  "@interop-lib/=lib/interop-lib/src/",
  "@solady/=lib/solady/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
