[rpc_endpoints]
zora_sepolia = "https://sepolia.rpc.zora.energy"
base_sepolia = "https://sepolia.base.org"
lisk_sepolia = "https://rpc.sepolia-api.lisk.com"
mode_sepolia = "https://sepolia.superseed.xyz"
superseed_sepolia = "https://53302.rpc.thirdweb.com"

[profile.default]
src = "src"
script = "scripts"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

fs_permissions = [
  { access='read', path='./configs' },
  { access='read', path='./test' },
  { access='write', path='./deployment.json' }
]

remappings = [
  "@interop-lib/=lib/interop-lib/src/",
  "@solady/=lib/solady/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
